import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import homeStyles from "@/styles/main.module.css";
import Navbar from "../../components/nav";
import SessionBars from "../../components/formula-next-session";
import ContructorsTable from "../../components/constructors-table.jsx"
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <SessionBars/>


        <div className={homeStyles.gridFour}>

        <div className={homeStyles.topTwoBlock}>
        
                <div>
                  Last sessions in lap times
                </div>
             
                <div>
                  Last sessions in lap times
                </div>
              
        </div>

        <div className={homeStyles.topTwoBlock}>
        
                <div>
                  Last sessions in lap times
                </div>
             
                <div>
                  Last sessions in lap times
                </div>
              
        </div>



        </div>
      
       
    </>
  );
}
